{% set name = "big-fish" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/big-fish-{{ version }}.tar.gz
  sha256: 60b91655d32b683e51d138940a0ec0c1bdfa9f063b65854fdbceae7edd52c527

build:
  noarch: python
  script: 
    - cp $RECIPE_DIR/requirements.txt $SRC_DIR/requirements.txt
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.0.2
    - mrc >=0.1.5
    - numpy >=1.16.0
    - pandas >=0.24.0
    - python >=3.6
    - scikit-image >=0.14.2
    - scikit-learn >=0.24.0
    - scipy >=1.4.1
    - tensorflow >=2.3.0

test:
  imports:
    - bigfish
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fish-quant/big-fish
  summary: Toolbox for the analysis of smFISH images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
